#!/usr/bin/env bash
# generate-version.sh — Generates AppVersion.swift from git tags.
# Called as an Xcode pre-build script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$REPO_ROOT/Pluginventory/Pluginventory/Generated"
OUTPUT_FILE="$OUTPUT_DIR/AppVersion.swift"

mkdir -p "$OUTPUT_DIR"

# Get version from git describe
if GIT_DESCRIBE=$(git -C "$REPO_ROOT" describe --tags --always 2>/dev/null); then
    # Strip leading 'v' if present
    GIT_DESCRIBE="${GIT_DESCRIBE#v}"

    # Check if this is an exact tag (release) or has commits ahead
    if [[ "$GIT_DESCRIBE" =~ ^([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
        # Exact tag match: e.g. "1.0.5"
        VERSION="$GIT_DESCRIBE"
        FULL_VERSION="$GIT_DESCRIBE"
        IS_RELEASE="true"
    elif [[ "$GIT_DESCRIBE" =~ ^([0-9]+\.[0-9]+\.[0-9]+)-(.+)$ ]]; then
        # Commits ahead of tag: e.g. "1.0.5-3-gabcdef0"
        VERSION="${BASH_REMATCH[1]}"
        FULL_VERSION="$GIT_DESCRIBE"
        IS_RELEASE="false"
    else
        # Fallback for hash-only (no tags)
        VERSION="0.0.0"
        FULL_VERSION="$GIT_DESCRIBE"
        IS_RELEASE="false"
    fi
else
    VERSION="0.0.0"
    FULL_VERSION="0.0.0"
    IS_RELEASE="false"
fi

cat > "$OUTPUT_FILE" << EOF
// Auto-generated by generate-version.sh — do not edit
enum AppVersion {
    static let version = "$VERSION"
    static let fullVersion = "$FULL_VERSION"
    static let isRelease = $IS_RELEASE
    static var displayVersion: String { isRelease ? version : fullVersion }
}
EOF
